# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Continuous Integration Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  #run-tests: [this is from estimagic]

    name: Run tests for ${{ matrix.os }} on ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        pip install -r requirements.txt
        #python -m pip install git+https://github.com/gboehl/grgrlib
        #python -m pip install git+https://github.com/gboehl/econsieve 
        #python -m pip install git+https://github.com/gboehl/emcwrap
        # use pypi version:
        python -m pip install grgrlib
        python -m pip install econsieve 
        python -m pip install emcwrap
        #python -m pip install numpy==1.20
        # no need to fix version:
        python -m pip install numpy
        python -m pip install h5py
        python setup.py install

    # # Uncomment to update stable pickle
    # - name: Update stable pickle
    #   if: runner.os == 'Ubuntu' && matrix.python-version == '3.8'
    #   run: |
    #     python pydsge/tests/export_getting_started_to_pkl.py

    - name: Test with pytest
      run: |
        pytest

    - name: Commit changed pickle
      uses: EndBug/add-and-commit@v7
      with:
        add: pydsge/tests/resources # only changes to 'resources/' folder are commited
        default_author: github_actions
        message: CI update of stable pickle
